# Generated by Django 5.0.1 on 2024-01-25 12:40

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articuloid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('nombrearticulo', models.CharField(default='', max_length=255)),
                ('descripcion', models.CharField(default='', max_length=255)),
                ('cantidad', models.CharField(default='', max_length=255)),
                ('condicion', models.CharField(default='', max_length=255)),
                ('localizacion', models.CharField(default='', max_length=255)),
                ('creado', models.DateTimeField(default=datetime.datetime.now)),
                ('archivo', models.ImageField(upload_to='excedente')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('vin', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('marca', models.CharField(default='', max_length=255)),
                ('modelo', models.CharField(default='', max_length=255)),
                ('year', models.CharField(default='', max_length=255)),
                ('tablilla', models.CharField(default='', max_length=255)),
                ('color', models.CharField(default='', max_length=255)),
                ('cantidad', models.CharField(default='', max_length=255)),
                ('condicion', models.CharField(default='', max_length=255)),
                ('localizacion', models.CharField(default='', max_length=255)),
                ('creado', models.DateTimeField(default=datetime.datetime.now)),
                ('archivo', models.ImageField(upload_to='excedente')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
