# Generated by Django 5.0.1 on 2024-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
