# Generated by Django 5.0.1 on 2024-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
